### PR TITLE
Update to mraerosol branch from Dom

### PR DESCRIPTION
**Pull request by climbfuji**
@AnningCheng-NOAA This PR updates your branches with the latest code from main, and contains a few updates for your merra2_aerosol_aware code. Please take a close look and let me know if you have questions. If you agree with the changes, then please merge the PR (this will update your branch in your github fork).

### CODE REVIEW

**Comment by AnningCheng-NOAA** [comment]
HI, Dom:

Have you performed a regression test with mraerosol=true and
ltaersosol=.false.? Where do you turn offf the reading and writing of
nifa_2d and nwfa_2d when mraerosol=True? Changes needed
in GFS_diagnostics.F90 to output nifa and nwfa.


Anning

**Comment by climbfuji** [comment]
Hi Anning,

so far I have only compiled it and made sure that the code in ccpp-physics makes sense and doesn't touch nifa/nwfa when mraerosol is true. There were a few bugs in your code that I fixed, and you should see this frorm the diffs in mp_thompson.F90 and module_mp_thompson.F90.

Once the ccpp-physics changes are in your branch, I'll work on an fv3atm PR for you.

If you have a regression test directory with the correct namelist and input data that you can share with me, I will make sure it runs in debug and prod mode.

Thanks,

Dom

**Comment by AnningCheng-NOAA** [comment]
Dom,
I have just merged the PR and clone to my local disk
at /scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model.

When I run  rt.sh -kc -l rt.conf1 > & o1 at  ufs-weather-model/tests, I get
a compilation error
/scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model/tests/build_fv3_001/FV3/ccpp/ccpp_prebuild.err

Something to do with the soil type. Could you take a look?

Anning

**Comment by climbfuji** [comment]
You need to pull in the latest fv3atm code from develop, because I updated your ccpp-physics code to the top of main.

Let me send you a first PR for fv3atm today/tomorrow. This won't have the GFS_diagnostics changes yet, but at least all the updates from develop.

**Pull request merged**
